CreateThread(function() -- TRAIN SPAWNS / SPAWN TRAINS
    SwitchTrainTrack(0, true)
    SwitchTrainTrack(3, true)
    SwitchTrainTrack(1, true)
    SwitchTrainTrack(2, true)
    SwitchTrainTrack(4, true)
    SwitchTrainTrack(5, true)
    SwitchTrainTrack(6, true)
    SwitchTrainTrack(7, true)
    SwitchTrainTrack(8, true)
    SwitchTrainTrack(10, true)
    N_0x21973bbf8d17edfa(0, 120000)
    SetRandomTrains(true)
  end)